### ISSUE TITLE
[RFC] use stale bot to close PRs that need work after period of inactivity

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#1561]
We have this comment in the README about reviewing submitted projects:

> We aim to be responsive when a pull request is open, but if a pull request remains idle for 2 weeks with feedback that prevents us from merging it we will close the pull request. 

I'd like to experiment with enabling this for just this subset of activity:

 - pull requests
 - labelled with `needs work`
 - after a period of 14 days
 - automatically close the issue and leave a comment

There are some projects coming up that look like an opportunity to test this out:

<img width="540" src="https://user-images.githubusercontent.com/359239/66821035-1f022a80-ef18-11e9-8249-24cd49f8494b.png">
 
And I think the `.github/stale.yml` config would look like this:

```yaml
pulls:
  daysUntilStale: 14
  daysUntilClose: 0
  onlyLabels: 
    - "needs work"
  exemptLabels:
    - "discussion"
   staleLabel: stale
   exemptAssignees: true
   markComment: >
      This pull request will be closed because it has not had recent activity after
      being reviewed. If you are still interested in adding your project to the site,
      please submit a new pull request and address the above feedback. Thank you
      for your contribution!
```
