### ISSUE TITLE
Redirecting to issues page instead of Repo Homepage

### ISSUE THREAD

**Issue by capturemathan** [up-for-grabs/up-for-grabs.net#2359]
Kudos to a wonderful website 🎉 . Some of the projects are being redirected to `REPO's homepage` instead of `REPO/issues`. Upon seeing the corresponding YAML files I learnt that URL's are pointed to REPO's homepage. (Eg) `https://github.com/dotnet/dotnet-api-docs` instead of `https://github.com/dotnet/dotnet-api-docs/issues`

**Comment by DhawalKhapre** [comment]
I would like to solve this issue @capturemathan 
I am a first-time here

**Comment by ritwik12** [comment]
@capturemathan Thanks!!. Can you give an example for that. As you can see we use two links. One is `site:` and another is `upforgrabs.link:`. The site one is intended to be a Homepage and the Link one is for issues i.e issues marked with particular label defined in `upforgrabs.name:`

```
name: Your Project Name Here
desc: A brief description of the project
site: https://example.org/your-project-link-here
tags:
  - tags
  - relevant
  - to
  - the
  - project
upforgrabs:
  name: up for grabs
  link: https://github.com/username/project/labels/up%20for%20grabs
```
