### ISSUE TITLE
CI: catch and report duplicate tags

### ISSUE THREAD

**Issue by shiftkey** [up-for-grabs/up-for-grabs.net#289]
There's likely a few different options here for tackling it, but we should catch scenarios where people submit a tag that's similar (but different) to a popular tag.

Here's a good example:

<img width="266" alt="screen shot 2015-12-12 at 9 18 16 am" src="https://cloud.githubusercontent.com/assets/359239/11757493/afcf3ac6-a0b1-11e5-8217-4e500638f285.png">

We should have one tag here for documentation-esque projects - I'm not fussed which - and if someone uses the other tag the build should fail.

Let's not go through the entire set of tags - let's just tackle this one for now and see what the solution looks like.

**Comment by shiftkey** [comment]
Another example: `nodejs` or `node.js` or `node`

**Comment by shiftkey** [comment]
Here's the current list, sorted by counts: https://gist.github.com/shiftkey/6eb57144d06275bdfdb0

**Comment by FleetAdmiral** [comment]
I'd like to take this up!

**Comment by shiftkey** [comment]
@FleetAdmiral sounds good!

**Comment by FleetAdmiral** [comment]
@shiftkey So i thought about it , and i couldn't decide as to how we'd decide if 2 tags relate to the same thing. For documentation , i guess its safe to say people putting anything like docs, document , etc would refer to the same thing , but what about tags like angular - how would we decide which tag it relates to (angular 1 or angular 2)?

**Comment by shiftkey** [comment]
@FleetAdmiral my initial thoughts on this would be to have a loose format ala YAML:

``` yaml
# group the angular versions under a unified tag
angular:
  type: framework
  alternatives:
  - angular1
  - angular2

# use the correct project name here
node.js:
  type: framework
  alternatives:
  - node
  - nodejs
```

This gives us a few things:
- the rules for grouping tags are simple and can be PRed by external contributors
- we can define tags on a case-by-case basis and migrate projects over
- we can annotate additional data related to each tag, for some better search abilities down the track

**Comment by dahlbyk** [comment]
For now, what if we just generated a tag directory and added a build step that requires all tags be present in the dictionary? If that tag directory were asserted to be in alphabetical order, it should be relatively easy to notice and prevent duplicates as they are about to be created.

For now, I'd propose a YAML associative array with empty values:

``` yaml
angular:
angular1:
angular2:
...
node:
node.js:
nodejs:
```

As we decide on tag properties (`type` is probably a good one, but what are valid values?), we can supplement on new lines without churning the existing list.
