### ISSUE TITLE
Add strategy/query fields to project YAMLs

### ISSUE THREAD

**Issue by aph3rson** [up-for-grabs/up-for-grabs.net#617]
I'm proposing that we split the `up-for-grabs` attribute in the project YAMLs into a handful of different fields, to improve the functionality on the website for repo hosts other than Github. In short, this includes:

* `name` - self-explanatory, name of the tag/label/etc.
* `strategy`/`type`/`host`/etc. - a way to tell what service/software hosts the content. This should be passed to `issueCount`, to determine what API calls to make to calculate the number of issues.  
* `query` - passed to `issueCount`, used to determine how many open issues to show on main page. Will depend on strategy used by `issueCount` in how to interpret this value (intended to be a query fed into an API).  
* `link` - literally the content of the `<a>` tag - could be a contribution guide, a list of open issues, a search for issues, etc. The user will be directed here if they'd like to contribute. This functionality has been requested previously - see #476   

Right now, the main problem is that `issueCount` is running off of the contents of the page, and doesn't appear to have access to the contents of the YAMLs - it primarily uses the contents of the `a` tag for finding how to count issues. Therefore, accessing these fields could be a challenge - it might be best to use [arbitrary HTML attributes](http://w3c.github.io/html/single-page.html?utm_source=dlvr.it&utm_medium=feed#embedding-custom-non-visible-data-with-the-data-attributes) on the label or similar.

**Comment by aph3rson** [comment]
I would love some further comments on this idea. Right now, it's somewhat-conflicting with another PR regarding properly counting GitHub issues (#462), but I'd be willing to do some more in-depth work on this idea, and scrap the previous idea (incorporating ideas from https://github.com/up-for-grabs/up-for-grabs.net/issues/607#issuecomment-300633183 anyways).

**Comment by shiftkey** [comment]
@aph3rson apologies for the delay in replying to your idea.

I didn't really get to thinking about this because there were a lot of overlapping and competing ideas about extending the project format and I didn't want to do it in an ad-hoc way. We also didn't have a good story about making API requests on the client and GitHub would get rate-limited, but now #1346 has support for caching stats from GitHub I'm ready to revisit this.

I need to think more about this for non-GitHub scenarios but I'm experimenting with this syntax to replace the `upforgrabs` element we have currently:

```yaml
projects:
  - source: github
    repo: ilkilab/agorakube
    label: up-for-grabs
```

This can stack to support multiple projects on GitHub:

```yaml
upforgrabs:
  - source: github
    repo: ilkilab/agorakube
    label: up-for-grabs
  - source: github
    repo: ilkilab/some-other-repository
    label: up-for-grabs
```

Or it can support organizations:

```yaml
upforgrabs:
  - source: github
    org: stanford-oval
    label: good first issue
```

The key here is that we start from a `source` to indicate where the repository is hosted, and the additional metadata can be used to build up the query and link.

I'm still in the process of reading over feedback and figuring out a roadmap for this, but let me know  if this is still something that interests you.
